added 2 addons of mine
SamsTheNerd/hexaddons pull request #15
Opened 2024-11-29 12:41 UTC by YukkuriC

2024-11-30 21:41 UTC, SamsTheNerd requested changes

2024-11-30 21:41 UTC, SamsTheNerd commented on index.html
why was this changed

2024-12-01 09:33 UTC, YukkuriC commented on index.html
I found the html tags not matched, was this intended?
if so, I can push -f to revert this

2024-12-02 16:33 UTC, YukkuriC commented on index.html
reverted, and this post still exists, amazing `_(:з」∠)_`

2024-12-12 05:16 UTC, merged